Feature/#4
prgrms-be-devcourse/BE-04-TICKETPARIS pull request #24
Opened 2023-09-05 06:03 UTC by charlesuu

## 👨‍💻 작업 사항

> **이슈 #4 **

---

### 📑 PR 개요

- 사용자 인증, 인가를 위해 구매자, 판매자 엔티티에 대한 CRUD 개발
- must have로 정의 된 기능만 우선으로 구현

---

### ✅ 작업 목록

- [ ]  구매자 엔티티 정의
- [ ]  판매자 엔티티 정의
- [ ]  테스트케이스 작성

---

### 🙏 리뷰어에게

---

### Prefix
> PR 코멘트를 작성할 때 항상 Prefix를 붙여주세요.
- `P1`: 꼭 반영해주세요 (Request changes)
- `P2`: 적극적으로 고려해주세요 (Request changes)
- `P3`: 웬만하면 반영해 주세요 (Comment)
- `P4`: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- `P5`: 그냥 사소한 의견입니다 (Approve)

2023-09-08 08:18 UTC, Hchanghyeon requested changes
현호님~ 코드 작성하시느라 너무 고생 많으셨습니다! 👍👍

궁금한거나 의논해야할 부분들에 대해서 코멘트 달아두었으니 확인 부탁드리겠습니다! 🙏🙏🙏 

감사합니다 🙇🙇

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +    public ApiResponse<CustomerResponse> findById(@PathVariable("customerId") Long customerId, HttpServletRequest httpServletRequest) {
`p1`

```suggestion
    public ApiResponse<CustomerResponse> findCustomerById(@PathVariable("customerId") Long customerId, HttpServletRequest httpServletRequest) {
```
팀 컨벤션으로 네이밍 변경부탁드립니다! 🙏

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    private String username;
`p3`

`@NotNull`을 추가하여 클라이언트로부터 값이 전달될 때 null값을 방지할 수 있으면 더 좋을 것 같습니다! 👍 Pattern을 사용하시니 필요한 곳에만 적용해주셔도 좋을 것 같아요!

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    }
`p2`

```suggestion
    public Customer toEntity() {
        return Customer.builder()
            .username(username)
            .password(password)
            .name(name)
            .email(email)
            .birthDate(birthDate)
            .phone(phone)
            .address(address)
            .build();
    }
```
toEntity() 메서드의 매개변수로 들어오는 값이 클래스 내 필드명과 동일한 경우에는 this를 붙여주지만 현재는  매개변수가 없고 내부 클래스에 있는 필드 값만 넣어주는 것으로 따로 this를 적어주지 않으면 될 것 같습니다!

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String email;
`p3`

어노테이션이 붙지 않은 필드명끼리는 개행하지 않고 붙여주어도 좋을 것 같은데 어떻게 생각하시나요?!

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String password;
`p1`

CustomerResponse는 클라이언트에게 응답해주는 dto로 **결국 클라이언트에게 전달되는 데이터**인데 password와 같은 정보를 넘겨주는 것은 좋지 않다고 생각합니다! 저의 경우 응답 값은 클라이언트 단의 화면 구성, 비지니스 로직을 생각해보고 그에 맞게 필요한 것만 보내려고하고 있습니다!

현호님은 이 부분에 대해서 어떻게 생각하실까요?

2023-09-08 08:18 UTC, Hchanghyeon commented on src/main/resources/mapper/CustomerMapper.xml
> +    </select>
`p1`

앞에서 언급드렸던 것 처럼 CustomerResponse에서도 필요한 값만 응답하듯 데이터베이스에서도 동일하게 필요한 값만 전달해주는 것이 좋을 것 같다고 생각합니다! 불 필요한 데이터를 보내는 것은 작지만 리소스 낭비이기도하고, 아무래도 Customer는 개인정보이기도 해서 정말 필요하지 않은 데이터는 네트워크를 타지 않는 것이 좋을 것 같다고 생각이 드네요!! 🤔

2023-09-08 08:18 UTC, Hchanghyeon commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +@ActiveProfiles("local")
`p2`

profile을 local로 두신 이유가 궁금합니다! 

아마 H2 데이터베이스 설정이 local 환경에 설정되어있어서 그러신 것 같기도 한데 현재 local, dev profile로 나누어진 목적이 사라지지 않을까요?! 저의 경우 test환경에 별도의 test 환경만을 위한 application.yml 파일을 생성하여 test시에는 test > resources 폴더에 있는 application.yml 파일을 읽도록 설정해두었습니다!

2023-09-08 13:09 UTC, charlesuu reviewed
리뷰 덕분에 정말 많이 배웠네요. 감사합니당

2023-09-08 13:09 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +    public ApiResponse<CustomerResponse> findById(@PathVariable("customerId") Long customerId, HttpServletRequest httpServletRequest) {
아 어제 결정하고는 깜박했네요. 감사드립니다~
f263d402ff4f18c61fa21498a1b9ff8505e54b69

2023-09-08 13:09 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    }
생각해보니 this로 구분될 부분이 없네요! 감사합니다
00f1773ea8e5ec4a568815698522a4de0c63a43a

2023-09-08 13:09 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    private String username;
이 리뷰 덕분에 json 값에 ""없이 null 이 들어오면 필드에 null로 파싱되어 들어간다는걸 알게 되었습니다.
해당 dto의 모든 필드에서 null체크가 되지 않고 있어서(pattern으로 null체크가 되지 않더라구요)  `@NotNull ` 추가 했습니다. 감사합니다.
00f1773ea8e5ec4a568815698522a4de0c63a43a

2023-09-08 13:09 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String password;
앗 당연한 부분인데 너무 고민없이 작성했네요.. ㅜ 정말 반성하게 됩니다!
회원정보를 조회하는 페이지를 가정하고 만든 기능인데요, 비밀번호를 제외하고는 다 조회할 법한 정보들이라 비밀번호만 제외하도록 수정했습니다.
bc1506ebd99628b6c51125a3786bb699382b65cc

2023-09-08 13:09 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String email;
개인적으로 각 필드가 한 칸씩 띄어있어야 가독성이 산다고 느껴져서 이렇게 적용해보았습니다.
가독성에 대한 주관은 사람마다 다를 수 있지만, 팀 코드에서는 통일된 컨벤션이 필요하다고 생각되어서 팀 회의 때 어떻게 통일하면 좋을지 의견을 나누어보면 좋을 것 같네요! 우선은 이대로 유지하고, 회의 이후 변경사항을 적용해보겠습니다~!

2023-09-08 13:09 UTC, charlesuu commented on src/main/resources/mapper/CustomerMapper.xml
> +    </select>
확실히 DTO만 수정해서 내려주기 보다, repository에서부터 민감정보는 제외하고 조회하는게 옳겠네요!
리뷰 적극 반영했습니다.
bc1506ebd99628b6c51125a3786bb699382b65cc

2023-09-08 13:09 UTC, charlesuu commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +@ActiveProfiles("local")
부끄럽지만 profile로 실행환경을 분리하는 개념에 대해서 크게 혼동하고 있었는데요. 창현님 리뷰 덕분에 제가 잘 못 알고 있는 점을 파악하고 다시 공부할 수 있었습니다(진짜 몰라도 너무 모르고 있었어서 뭘 배웠다고 다 적기도 민망하네요..ㅋㅋㅋㅋ). 여튼 한 두시간 찾아본 끝에 개념을 탄탄히 할 수 있었습니다!  그 뒤에 @ActiveProfiles은 삭제하고 test/resources 하위의 application.yml을 읽어오도록 처리했습니다.
 단순히 리뷰사항 반영하고 끝이 아니라 몰랐던 부분을 잡고 갈 수 있었어서 정말 좋았네요. 의도한건 아니시겠지만?! 깊이 감사드립니다리~~!

2023-09-08 15:42 UTC, hanjo8813 reviewed
👍

2023-09-08 15:42 UTC, hanjo8813 commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +	private final CustomerService customerService;
`p4`
한칸 띄워주기~
다른곳도 동일하게 맞춰주세요

\+ 그리고 요 파일만 indent 인식이 tab으로 되네요
intellij auto save formatting 설정을 해보아요

2023-09-08 15:42 UTC, hanjo8813 commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +	private String name;
`p3`
위 필드들은 Customer와 Seller가 같은 validation 규칙을 가지게 될텐데, 
중복을 줄이고 통일성을 높히기 위해 ConstraintValidator로 커스텀 어노테이션 추가를 고민해보세요

https://velog.io/@ljks789/spring-ConstraintValidator%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

2023-09-08 15:42 UTC, hanjo8813 commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +
`p5`
시간 데이터의 응답 형식은 통일되었나요?
영주님 코드에서는 `yyyy-MM-dd HH:mm:ss`으로 봤어서요~

2023-09-08 15:45 UTC, jay-so reviewed
현호님! 코드 작성하느라 수고하셨습니다!👍👍
궁금한 점 및 의논해야 할 점들에 대해서 코멘트를 달아두었으니 확인 부탁 드리겠습니다!! 😀😀

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$", message = "비밀번호는 8자 이상 20자 이하로 입력해주세요. (<영어, 숫자, 특수문자> 포함, 공백불가)")
`P2`: 비밀번호 생성을 위한 제한 조건을 정규 표현식으로 정의하기 보다는 아래의 자료를 참고하여 커스텀 `@Validation` 또는 Passy 라이브러리 통해 비밀번호 생성 규칙 정의 및 비밀번호 유효성 체크를 하는 검증하는 방식이 어떨까요? 
https://stackabuse.com/spring-custom-password-validation/ 
 https://www.baeldung.com/java-passay

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    @Pattern(regexp = "^[a-zA-Z0-9._%+-]{1,64}@[a-zA-Z0-9.-]{1,255}\\.[a-zA-Z]{2,}$", message = "이메일은 320자 이하로 입력해주세요.(공백 미포함)")
`P5`: 정규 표현식을 통해 이메일 Validation으로 주신 것 너무 좋은 것 같아요!! 👍👍 
찾아보니 `@Email`어노테이션의 경우, `@`문자가 없는 경우에만, 유효하지 않은 이메일로 판단하지만, 이메일 주소를 판단하는데 비 정상적인 패턴을 해도 옳은 이메일로 취급한다고 하네요! 따라서 이메일을 꼼꼼하게 체크하려면 정규 표현식을 사용해야 한다는 것 리뷰하면서 알아가네요. 😀😀
https://see-one.tistory.com/14
https://www.baeldung.com/java-email-validation-regex

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String password;
`P2`: 창현님의 리뷰 의견과 같이 응답 값에는 사용자의 password 필드를 넘겨 주는 것이 좋지 않다고 생각합니다!

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +    void createAccount(Customer item);
`P1`: 팀 컨벤션에서 Repository에서 사용하는 메소드명은 save로 통일하기로 했습니다! 반영해주세요!

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +public interface CustomerRepository {
`P3` : CustomerRepository를 interface로 설정, MybatisCustomerRepository를 통해 구현하는 이유가 있으신가요?? MybatisCustomerRepository의 내용 그대로 CustomerRepository에서 구현해도 될 것 같습니다!

2023-09-08 15:45 UTC, jay-so commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +    @GetMapping("/{customerId}")
`p1`:  회원 정보 조회의 경우, `/api/customers/{id}` 로  작성하기로 했습니다! 변경 부탁드립니다!

2023-09-09 05:35 UTC, kylekim2123 reviewed
현호님 고생 많으셨습니다 ㅎㅎ
반영할 건 반영해주시고 다시 코멘트 부탁드려요~

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/resources/data.sql
> +VALUES ('COMPLETED', 2, 8);
`P1`
- data.sql 형식은 해당 PR에서 포매팅 하지 않는게 좋을 것 같습니다.
- IntelliJ code style에서 sql에 대한 자동 포매팅은 끄시는 것도 좋겠네요!

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/mapper/member/CustomerMapper.java
> +    boolean existById(Long customerId);
`P1`
- 협의한 결과에 따르면 existsById로 네이밍 통일하기로 했습니다. s가 빠졌네요~
- Repository 단의 메서드명도 같이 변경 해주세요!

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/resources/mapper/CustomerMapper.xml
> +    <select id="existById" resultType="boolean">
`P1`
- Wrapper type으로 통일하기로 한만큼, Boolean으로 적어주시면 좋을 것 같습니다.

2023-09-09 05:35 UTC, kylekim2123 commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +			.hasMessageContaining("이미 가입된 username 또는 email로 요청");
`P4`
- hasMessageContaining() 대신 hasMessage()를 사용해보면 어떨까요?
- 전자는 해당 문자열이 포함되기만 해도 통과 되지만, 후자는 정확히 일치해야 해서 더 메시지를 잘 검증할 수 있을 것 같아요.

2023-09-09 05:35 UTC, kylekim2123 commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +@Transactional
`P1`
- 현재 테스트 클래스 단위로 Transactional 애너테이션이 붙어 있어서, 모든 메서드에 일괄적으로 적용이 되네요
- 조회 테스트에는 따로 필요 없기 때문에, 메서드 별로 따로 붙여주시면 어떨까요?

2023-09-09 05:35 UTC, kylekim2123 commented on src/test/java/com/programmers/ticketparis/service/member/CustomerServiceTest.java
> +	@Test
`P1`
- 다른 테스트 메서드와 마찬가지로 DisplayName 붙여주세요!

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/service/member/CustomerService.java
> +@Slf4j
`P2`
- Logger가 따로 쓰이진 않은 것 같은데, 붙여주신 이유가 있을까요?

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
> +                throw new CustomerException(ExceptionRule.CUSTOMER_ALREADY_REGISTERED, List.of(customer.getUsername()));
`P1`
- 연결된 예외(Chained Exception)에 대한 처리를 하려고 하신 것 같습니다.
- 이때는 원인 예외(Cause Exception)을 따로 넣어주어야, 나중에 스택 트레이스에서 커스텀 예외(CustomerException)가 발생한 실제 원인(DuplicateKeyException)을 보여줄 수 있습니다.
- 그러려면 New를 통해 예외를 생성할 때, 생성자에서 Throwable 타입으로 원인 예외를 받아서, super()를 통해 넘겨줘야 합니다.
- 커스텀 예외의 부모인 BusinessException에 생성자 오버로딩을 통해서 구현할 수 있을 것 같네요!
- [참고] https://www.baeldung.com/java-chained-exceptions#2-with-chaining

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    }
`P2`
- 생성자 대신 정적 팩토리 메서드 from을 고려해보시는 건 어떨까요?

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
> +    CUSTOMER_ALREADY_REGISTERED(HttpStatus.BAD_REQUEST, "이미 가입된 username 또는 email로 요청");
`P1`
- 현재 controller, service에서는 가입을 create라는 동사로 쓰고 있고, 여기서는 register라는 동사로 쓰고 있네요.
- 통일성을 위해서 하나로 맞춰주시면 좋을 것 같습니다.

2023-09-09 05:35 UTC, kylekim2123 commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +public interface CustomerRepository {
안그래도 이거 관련해서도 얘기 해봐야 할 것 같아요. repository의 다형성을 고려해서 ORM 이름을 앞에 붙여주는 네이밍으로 갈지, 아니면 어차피 이번 프로젝트는 mybatis 말고는 다른 ORM을 사용할 일이 없으니까 재훈님 말대로 CustomerRepository로 갈지에 대해서요!

2023-09-09 15:23 UTC, mentor-tyler reviewed
<img src="https://media0.giphy.com/media/K3Sbp8fOgKye4/giphy.gif"/>

2023-09-09 15:23 UTC, mentor-tyler commented on src/main/java/com/programmers/ticketparis/dto/ApiResponse.java
> +    private final LocalDateTime timestamp = LocalDateTime.now();
별거 아닐수 있지만, java.sql.Timestamp 와 혼동이 있을수 있기에 차라리 변수명을 localDateTime으로 지정하는것도 좋아보입니다.

2023-09-09 15:23 UTC, mentor-tyler commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +    void createAccount(Customer item);
ㅋㅋ 조금은 더 부드러운 어조로~

> 팀 컨벤션에서 Repository에서 사용하는 메소드명은 save로 통일하기로 했던것 같아요~ 확인 부탁드립니다~

2023-09-09 15:23 UTC, mentor-tyler commented on src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
> +            if (e.getMessage().contains("USERNAME NULLS FIRST")) {
나눠서 처리해야 할 이유가 있을지 고민이 되네요. 이름 중복과 아래 email 중복에 따라 처리가 달라지는지도 궁금하고요.

2023-09-09 15:23 UTC, mentor-tyler commented on src/main/resources/mapper/CustomerMapper.xml
> +        where customer_id = #{customerId}
```suggestion
        SELECT 
            customer_id, 
            username, 
            name, 
            email, 
            birth_date, 
            phone, 
            address
        FROM customer
        WHERE customer_id = #{customerId}
```

예약어는 대문자로 해도 괜찮을것 같고, 적당한 포맷팅으로 가독성에 도움을 줄수도 있을것 같아요. 팀내에서 이야기 나눠보세요 ㅎ cc. @prgrms-be-devcourse/new-tyler

2023-09-11 12:32 UTC, charlesuu reviewed
@kylekim2123 @mentor-tyler @hanjo8813 @jay-so 
리뷰 모두 반영 되었습니다~~! 이번에도 배운 점이 너무 많았네요. 꼼꼼한 리뷰 남겨주셔서 모두모두 감사드립니다!~!

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +	private final CustomerService customerService;
넵 포맷터 세팅을 통해 자동적으로 한 칸 띄어지도록 개선했습니다~!
6067a5e098339a34edd35d2e040ce77ae76cf837

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +	private String name;
Seller에서 중복되며, 검증 조건이 복잡한 필드들에 대해서 커스텀 어노테이션 추가하고 적용했습니다~!!
92ae3ff1c1904362b90547a49e15e9f64b0072e4

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +
앗 날짜 형식 통일은 아직 못했습니다ㅜㅜ 의논해 봐야겠네요. 우선 영주님 형식으로 맞추었습니다. 그 과정에서 응답에 날짜가 누락되고 있는 오류도 발견해서 고쳤습니다!! 감사합니다.
30a3e84e803293c1a68e05d8834acc8861fedab3

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerCreateRequest.java
> +    @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$", message = "비밀번호는 8자 이상 20자 이하로 입력해주세요. (<영어, 숫자, 특수문자> 포함, 공백불가)")
너무 좋네요~!! 어제 말씀 나누었지만, 일정 여유 생기는대로 Passy한 번 적용해보겠습니다.
라이브러리는 적용 못 했지만, Seller 도메인 구현된 뒤에 검증 로직에 중복이 생길 것 같아서 커스텀 어노테이션 구현한 뒤 적용했습니다~
92ae3ff1c1904362b90547a49e15e9f64b0072e4

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    private String password;
넵 응답에서 password 제외하도록 수정했습니다~!
bc1506ebd99628b6c51125a3786bb699382b65cc

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +    void createAccount(Customer item);
Repository에서의 네이밍은 save로 하는 게 맞겠네요~! 팀 컨벤션에 맞춰서 수정했습니다.
aebff1aaf410a944d16781bf263e6be40e727d9e

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/repository/member/CustomerRepository.java
> +public interface CustomerRepository {
넵, 기록 차원에서 남기자면 어제 결정된 대로 인터페이스 두는 방식으로 유지하겠습니다~~!

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/controller/member/CustomerController.java
> +    @GetMapping("/{customerId}")
클래스 어노테이션에 @RequestMapping("/api/customers")이 정의되어 있습니다~!!
그러면 요청 URI가 `/api/customers/{customersId}` 가 되는데요. Path Variable의 경우 어제 회의로 결정된대로 도메인명을 붙여서 유지하겠습니다~!

2023-09-11 12:32 UTC, charlesuu commented on src/main/resources/data.sql
> +VALUES ('COMPLETED', 2, 8);
생각해보니 java 파일 외에 공유되는 resources 파일은 수정되지 않도록 세팅해야겠네요!!
자동 포매팅 껐습니다. 리뷰 감사합니다~~!
e52c9eddd091f3fd853ed7ac5a435ae979fb3328

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/mapper/member/CustomerMapper.java
> +    boolean existById(Long customerId);
앗 컨벤션 준수가 미흡했네요~! 꼼꼼하게 봐주셔서 감사합니다 영주님
db0f033c6500c82b97bc7d90ca772cec7bf4cdd4

2023-09-11 12:32 UTC, charlesuu commented on src/main/resources/mapper/CustomerMapper.xml
> +    <select id="existById" resultType="boolean">
그렇네요~! repository와 매퍼 클래스에도 적용했습니다. 감사합니다~
db0f033c6500c82b97bc7d90ca772cec7bf4cdd4

2023-09-11 12:32 UTC, charlesuu commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +			.hasMessageContaining("이미 가입된 username 또는 email로 요청");
두 메서드 차이를 모르고 있었는데 이번 기회에 배웠네요.
현 상황에는 hasMessage로 적용하는게 옳아보입니다.
위 테스트 뿐 아니라 다른 테스트에도 적용했습니다. 감사합니다~
3de093c84eedcc0512beecfd8574236bcea4db45

2023-09-11 12:32 UTC, charlesuu commented on src/test/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepositoryTest.java
> +@Transactional
조회 테스트에는 제외하는게 맞네요.
조회 외 테스트에만 따로 @Transactional 붙여주고, 클래스에서는 제거했습니다~!

2023-09-11 12:32 UTC, charlesuu commented on src/test/java/com/programmers/ticketparis/service/member/CustomerServiceTest.java
> +	@Test
빼먹었군요. 꼼꼼한 리뷰 감사합니다~~! 붙여 두었습니당.
3de093c84eedcc0512beecfd8574236bcea4db45

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/service/member/CustomerService.java
> +@Slf4j
앗 테스트용으로 붙여두었다가 어노테이션은 깜박하고 그대로 두었네요. 다른 계층에 있는 어노테이션까지 삭제했습니다~~!!
db0f033c6500c82b97bc7d90ca772cec7bf4cdd4

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +    }
좀 더 명확한 의미부여를 위해서 from 도입 좋겠네요~!!
팀 내 코드 스타일 통일을 위해서도 이게 맞는 것 같아요 생성자는 private으로 막아두고, from을 통해 생성되도록 변경했습니다.
aebff1aaf410a944d16781bf263e6be40e727d9e

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/exception/ExceptionRule.java
> +    CUSTOMER_ALREADY_REGISTERED(HttpStatus.BAD_REQUEST, "이미 가입된 username 또는 email로 요청");
만들면서 고민되었던 부분인데 디테일하게 잘 잡아주셨네요!!
다시 생각해보니 통일성있게 가는게 좋겠다고 생각되어서 맞춰두었습니다.
05d5a898b7e2bdf69ec073cff40042ac0e7a3596

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/ApiResponse.java
> +    private final LocalDateTime timestamp = LocalDateTime.now();
혼동할 수 있는 여지가 있네요!! 변수명 변경했습니다. 디테일한 부분 봐주셔서 감사합니다 멘토님~!!
74d0b3cfc857636203874ebf48ae0d1a58a1049b

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
> +            if (e.getMessage().contains("USERNAME NULLS FIRST")) {
리뷰 받고나니 정말 많은 고민을 할 수 있었습니다.
 우선 분기를 한 이유에 대해 설명드리자면, 최종 응답인 ErrorResponse에서 오류를 일으킨 필드 값을 요구하고 있습니다. 위 분기를 통해서 중복된 필드 값만 넘겨주려는 시도를 했었는데요. 둘 다 중복인 경우에 대한 처리도 안 되어있고, 분리를 위한 로직도 세련되지 못하다고 생각되어서 위 코드는 완전히 제거했습니다. 대신에 existsByUsernameOrEmail 메서드를 만들어서 각 필드에 대한 분기 없이 예외 처리하도록 바꾸었습니다.
 사실 중복 사용자 체크에 대한 부분은 따로 API가 존재하는게 맞지 않나라는 생각이 들어서, 일정 여유가 생기면 이름 중복, 아이디 중복을 체크하는 api를 따로따로 만들어 볼 예정입니다~~!

2023-09-11 12:32 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/repository/member/MyBatisCustomerRepository.java
> +                throw new CustomerException(ExceptionRule.CUSTOMER_ALREADY_REGISTERED, List.of(customer.getUsername()));
오 단순히 체이닝만 하면 스택 트레이스가 끊기는군요. 너무 좋은 지식 감사합니다!!! 정말 공부 많이 됐어요.
위 메서드는 분기 방식 관련해서 이슈가 좀 있었어서 완전히 없애고, 다른 방식으로 구현했는데요. 그 과정에서 연결된 예외가 없어져서 이번에는 활용하지 못 했습니다. 하지만 프로젝트 진행하다가 한 번쯤을 나올 수 있는 상황이라 다음에 꼭 써먹을 수 있을 것 같네요!! 감사합니다 영주님

2023-09-11 12:32 UTC, charlesuu commented on src/main/resources/mapper/CustomerMapper.xml
> +        where customer_id = #{customerId}
예약어는 대문자가 국룰이죠~!!  포맷팅 관련해서도 내일 팀 회의 바로 해봐야겠습니다. 훨씬 가독성이 사는 것 같아요. 리뷰 감사합니다 멘토님~~!

2023-09-12 07:52 UTC, charlesuu commented on src/main/java/com/programmers/ticketparis/dto/member/CustomerResponse.java
> +
@hanjo8813 재원님ㅜㅜ. 그동안 리뷰어가 반영 사항 확인 후 resolve conversation 해주신다는 걸 모르고 있었습니다. 코멘트에 적용 커밋 주소를 남기지 않았던 것도 같은 이유에서였는데요. 뒤늦게 배려 없는 행동이었다는 걸 알게 되어서 죄송했습니다... 그동안 일일이 변경 사항 찾아주셨나요?ㅜㅜㅜ
 뒤늦게나마 적용 커밋 모두 남겨놓았습니다. `그동안의 후의에 감사드립니다리!`

2023-09-12 08:10 UTC, Hchanghyeon approved these changes

2023-09-12 14:35 UTC, merged